# Generated by Django 4.1.1 on 2022-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OrderDate", models.DateField()),
                ("region", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=64)),
                ("product", models.CharField(max_length=64)),
                ("qty", models.IntegerField()),
                ("UnitPrice", models.FloatField()),
            ],
        ),
    ]
